### PR TITLE
[WIP] Fix the rest of the green

### PR DESCRIPTION
**Pull request by Minion3665**
- [x] Presence SVGs
- [x] Create server & Discovery buttons
- [x] Call indicators in chat
- [ ] Call popup
- [x] Talking indicator rings

At least some of each of these are affected, although not necessarily all of them (for example some presence SVGs were styled already and some were not)

### CODE REVIEW

**Comment by CanadaHonk** [comment]
Some great catches, thanks! (Feel free to just finalise this and I'll merge these ones and then if you do anymore you could open a new PR.)

**Comment by Dziurwa14** [comment]
talking indicator rings

.avatarSpeaking-2IGMRN {
  box-shadow: inset 0 0 0 2px var(--old-green),inset 0 0 0 3px #2f3136;
}

**Comment by Minion3665** [comment]
I've done everything intended, apart from the accept call buttons which still need to be fixed. It should be working, apart from the call icons in chat for which you'll need to push to the main branch of your repo (they rely on a call icon in there). 

@Dziurwa14 I found that I needed a different selector for speaking avatars than the one you said here, I've gone ahead and used mine but if you or anyone else knows if that `-2IGMRN` changes per-person or per-something-else I'd like to know, if it does we could consider updating stuff (possibly the whole repo?) to use `*[class*="avatarSpeaking-"]` instead of `.avatarSpeaking-randomcode` or similar.

I'm going to go ahead and fix the conflicts in main.css now, and then we should be good to test and merge

**Comment by CanadaHonk** [comment]
Nice. We could likely just use two selectors for it (or a wildcard as you said).

**Comment by CanadaHonk** [comment]
Gonna merge and tweak some stuff myself, thanks!

**Pull request merged**
