### PR TITLE
Reverted all the new green elements back to old green

### PR DESCRIPTION
**Pull request by Compwnter**

### CODE REVIEW

**Comment by CanadaHonk** [comment]
Please use actual commit names and comments, also hardcoded should fix some of these too.

**Comment by Compwnter** [comment]
> 
> 
> Please use actual commit names and comments, also hardcoded should fix some of these too.

Alright. I'm not fully sure how to categorize with comments (probably due to me being atypical) but hopefully hardcoded fixes these issues.

**Comment by CanadaHonk** [comment]
I mean comment what each one does, not categorise.

**Comment by Compwnter** [comment]
> 
> 
> I mean comment what each one does, not categorise.

Ah.

**Comment by CanadaHonk** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
