### PR TITLE
Update wordmark.css

### PR DESCRIPTION
**Pull request by Dabs-Rulez**
Fixes wordmark on discord canary

### CODE REVIEW

**Comment by CanadaHonk** [comment]
By just changing these classes you break it for non-Canary users..?

**Comment by CanadaHonk** [comment]
Additionally, please put your several PRs under one, it makes merging and general management a pain. (Also my above comment applies to them all, I'm pretty sure.)

**Comment by Dabs-Rulez** [comment]
> By just changing these classes you break it for non-Canary users..?

You can also add classes for the canary one and the non canary ones. Then both will work

**Comment by CanadaHonk** [comment]
It's your PR(s)?

**Comment by SupDos** [comment]
It's broken on stable now too, so this shouldn't matter anymore

**Comment by Dabs-Rulez** [comment]
> It's your PR(s)?

Since it is now broken on stable and ptb, can you please merge my PR asap.

**Comment by CanadaHonk** [comment]
Sigh

**Pull request merged**
