### PR TITLE
Revert Discord watermark on Windows

### PR DESCRIPTION
**Pull request by ghost**
I got the old watermark before and added it to my own theme, and I wanted to reuse it for this one.

### CODE REVIEW

**Comment by keanuplayz** [comment]
Sometimes I wish people that plan on making a PR actually check a project's entire codebase before making it.
Don't we [already have this?](https://github.com/Goose-Nest/GT-RevertRebrand/blob/main/src/components/wordmark.css)

**Comment by CanadaHonk** [comment]
This is already implemented in `src/components/wordmark.css` (also avoid `src/main.css`, it is unused and kept for backwards compatibility).

**Comment by ghost** [comment]
Is `src/components/wordmark.css` even used? Because when I have the theme enabled, I still have the new watermark 🤔

**Comment by keanuplayz** [comment]
> Is `src/components/wordmark.css` even used?

https://github.com/Goose-Nest/GT-RevertRebrand/blob/19b651381aeff0b0625f1ab936bc716bdc1eb2e5/src/main.scss#L24

**Comment by ghost** [comment]
> Because when I have the theme enabled, I still have the new watermark 🤔

image

**Comment by CanadaHonk** [comment]
The latest version is v5.1, your install is very outdated.

**Comment by ghost** [comment]
Oh I'm dumb lol

**Pull request closed without merging**
