### PR TITLE
Complete SCSS rewrite and issue fixes

### PR DESCRIPTION
**Pull request by georgetzlp**
Resolves most issues from this repo and is written in SCSS

### CODE REVIEW

**Comment by CanadaHonk** [comment]
This changes a lot of unneeded things?

**Comment by georgetzlp** [comment]
The only "unneeded" thing I can think of is the SCSS rewrite, which I find quite a good thing; is there something i'm missing?

**Comment by CanadaHonk** [comment]
> The only "unneeded" thing I can think of is the SCSS rewrite, which I find quite a good thing; is there something i'm missing?

I agree a SCSS rewrite is good; however this PR also does various unneeded changes:
- Changing theme.css filename
- Changing main file to `index.scss` (`src` subdir is used for all source files)
- Changing things in `gnTheme.mjs`, `README.md`
- Unneeded personal-ish comments in CSS

**Comment by georgetzlp** [comment]
- I'm not sure which file you're talking about, the only thing I can think of is the main file which you point out next
- The change of the main file name was personal preference, I can change that no problem
- I wasn't really sure what that file was really, I can change it back
- I feel like most of those comments would be useful for people who might want to edit the theme themselves, if you find some being "too personal and unneeded", please point them out with a request for changes

**Comment by CanadaHonk** [comment]
> I'm not sure which file you're talking about

`src/main.scss`

> if you find some being "too personal and unneeded"

Meant ones like:
- `// oh my god i didn't even think about ids having a heigher specificity`
- `//* I changed the whole formatting in this file, hope it's not such a big problem
// I also have to say, this is very accurate to the old reactions; good job `

**Comment by georgetzlp** [comment]
- I replaced src/main.scss for index.scss, I felt it made more sense and that it looked a bit more "natural" I guess.
- oh, sure I can get rid of those; forgot I had even kept them lol

**Comment by CanadaHonk** [comment]
I'll likely just rewrite in SCSS in the future myself as to avoid various issues stated; but still thanks for the PR!

**Comment by georgetzlp** [comment]
Alright, no problem

**Pull request closed without merging**
